config/routes.rb
PartyFinder::Application.routes.draw do
  resources :parties
  get '/locations/cities_for' => 'locations#cities_for'

  devise_for :admins

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  root :to => 'parties#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/cities.rb
class Cities < ActiveRecord::Base
  belongs_to :state
  attr_accessible :name, :state
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
  attr_accessible :name, :state

  def self.names_with_ids(state_id)
    self.where(state_id: state_id).order("name ASC").map {|c| [c.name, c.id]}
  end
end

app/models/party.rb
class Party < ActiveRecord::Base
  belongs_to :city
  belongs_to :state
  belongs_to :user
  attr_accessible :description, :latitude, :longitude, :name, :start_at, :street, :street_extra, :street_number, :city_id, :user_id

  validates_presence_of :name, :description, :start_at, :street

  validates_each :start_at do |record, attr, value|
    record.errors.add(attr, 'deve ser no futuro.') if value.nil? || value.blank? || (value.past? && record.new_record?)
  end

  geocoded_by :full_street_address
  after_validation :geocode

  scope :future, where("start_at > ?", 10.hours.ago).order("start_at ASC")

  def as_json(options={})
    {
      :id => self.id,
      :name => self.name,
      :description => self.description,
      :latitude => self.latitude,
      :longitude => self.longitude,
      :address =>{
        :street => self.street,
        :number => self.street_number,
        :extra => self.street_extra,
        :city => self.city.name,
        :state => self.state.uf,
      },
      :start_at => self.start_at
    }
  end

  def state
    self.city.state
  end

  def full_street_address
    [street, street_number, city.name, state.uf].compact.join(', ')
  end

  def full_address
    street + ', ' + street_number.to_s + "#{'/' + street_extra if street_extra.present?}"  + ', ' + city.name + '/' + state.uf
  end
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :cities
  attr_accessible :name, :uf

  def self.names_with_ids
    self.order("name ASC").map {|c| [c.name, c.id]}
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :parties
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def cities_for
    if params[:state_id].present?
      render json: City.where(state_id: params[:state_id]).order("name ASC").map{|city|
        {id: city.id, name: city.name}
      }, status: 200
    else
      render nothing: true, status: :unprocessable_entity
    end
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  # GET /parties
  # GET /parties.json
  def index
    @parties = Party.scoped
    if params[:la].present? and params[:lo].present? and params[:la].to_i and params[:lo].to_i
      @parties = @parties.where("latitude BETWEEN ? AND ? AND longitude BETWEEN ? AND ?", params[:la].to_i - 10, params[:la].to_i + 10, params[:lo].to_i - 10, params[:lo].to_i + 10).order("start_at ASC")
    else
      @parties = @parties.future
    end
    @parties = @parties.page(params[:page]).per(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json {
        render json: {
          data: @parties,
          next_page: @parties.last_page? ? nil : parties_url(page: @parties.current_page+1, format: :json),
          prev_page: @parties.first_page? ? nil : parties_url(page: @parties.current_page-1, format: :json)
        }
      }
    end
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
    @party = Party.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @party }
    end
  end

  # GET /parties/new
  # GET /parties/new.json
  def new
    @party = Party.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @party }
    end
  end

  # GET /parties/1/edit
  def edit
    @party = current_user.parties.find(params[:id])
    @selected_state = @party.city.state_id
    @selected_city = @party.city.id
  end

  # POST /parties
  # POST /parties.json
  def create
    @party = Party.new(params[:party])
    @party.user = current_user

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render json: @party, status: :created, location: @party }
      else
        format.html { render action: "new" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parties/1
  # PUT /parties/1.json
  def update
    @party = current_user.parties.find(params[:id])

    respond_to do |format|
      if @party.update_attributes(params[:party])
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party = current_user.parties.find(params[:id])
    @party.destroy

    respond_to do |format|
      format.html { redirect_to parties_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def brazil_states
    State.names_with_ids
  end

  def brazil_cities(state_id)
    state_id ||= State.first.id
    City.names_with_ids(state_id)
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PartyFinder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>Party finder</h1>
  <% if user_signed_in? %>
    <p><%= link_to "Logout", destroy_user_session_path, :method => :delete %></p>
  <% else %>
    <p><%= link_to "Login", new_user_session_path %></p>
  <% end %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>
  <footer>
    <hr>
    <p>Party finder - Desenvolvido para iOS ou Android (a decidir)</p>
    <p>Parte web desenvolvida com <%= link_to "Ruby on Rails", "http://rubyonrails.org/", :target => "_blank" %></p>
    <p>Por <%= mail_to "eduardofsilva182@gmail.com", "Eduardo Ferreira e Silva", :encode => "hex" %> e <%= mail_to "jr.schnorr@gmail.com", "Sérgio Schnorr Júnior", :encode => "hex" %></p>
  </footer>
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-35682668-1']);
    _gaq.push(['_setDomainName', 'herokuapp.com']);
    _gaq.push(['_trackPageview']);
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
</body>
</html>

app/views/parties/_form.html.erb
<%= form_for(@party) do |f| %>
  <% if @party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
      <% @party.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :street_number %><br />
    <%= f.number_field :street_number %>
  </div>
  <div class="field">
    <%= f.label :street_extra %><br />
    <%= f.text_field :street_extra %>
  </div>
  <div class="field">
    <%= select nil, 'state_id', brazil_states, {selected: @selected_state}, {class: "state"} %><br>
    <%= select 'party', 'city_id', brazil_cities(@selected_state), {selected: @selected_city}, {class: "city"} %>




  </div>
  <div class="field">
    <%= f.label :start_at %><br />
    <%= f.datetime_select :start_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parties/edit.html.erb
<h1>Editing party</h1>

<%= render 'form' %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<h1>Listing parties</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Descrição</th>
    <th>Rua</th>
    <th>Número</th>
    <th>Complemento</th>
    <th>Cidade</th>
    <th>Estado</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Início</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parties.each do |party| %>
  <tr>
    <td><%= party.name %></td>
    <td><%= party.description %></td>
    <td><%= party.street %></td>
    <td><%= party.street_number %></td>
    <td><%= party.street_extra %></td>
    <td><%= party.city.name %></td>
    <td><%= party.state.name %></td>
    <td><%= party.latitude %></td>
    <td><%= party.longitude %></td>
    <td><%= time_tag party.start_at, l(party.start_at, :format => :short), :title => l(party.start_at)  %></td>
    <td><%= link_to 'Show', party %></td>
    <% if user_signed_in? and current_user == party.user %>
      <td><%= link_to 'Edit', edit_party_path(party) %></td>
      <td><%= link_to 'Destroy', party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= paginate @parties %>

<%= link_to 'New Party', new_party_path %>

app/views/parties/new.html.erb
<h1>New party</h1>

<%= render 'form' %>

<%= link_to 'Back', parties_path %>

app/views/parties/show.html.erb
<p>
  <b>Nome:</b>
  <%= @party.name %>
</p>

<p>
  <b>Descrição:</b>
  <%= @party.description %>
</p>

<p>
  <b>Logradouro:</b>
  <%= @party.full_address %>
</p>

<p>
  <b>Latitude:</b>
  <%= @party.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @party.longitude %>
</p>

<p><%= link_to "Google Maps", "http://maps.google.com.br/?q=@#{@party.latitude},#{@party.longitude}", :target => "_blank" %></p>

<p>
  <b>Começo:</b>
  <%= l @party.start_at %>
</p>


<%= link_to 'Editar', edit_party_path(@party) %> |
<%= link_to 'Voltar', parties_path %>